const kelimeListesi = [
    { kelime: "YAZILIMCI", ipucu: "Kod yazarak hayatını kazanan kişi." },
    { kelime: "ARAYÜZ", ipucu: "Kullanıcının programla etkileşime girdiği ekran." },
    { kelime: "İSTİSNA", ipucu: "Genel kuralın dışında kalan durum." },
    { kelime: "DONANIM", ipucu: "Bilgisayarın fiziksel parçalarının bütünü." },
    { kelime: "ALGORİTMA", ipucu: "Bir problemin çözümündeki mantıksal adımlar." },
    { kelime: "SUNUCU", ipucu: "Verileri depolayan ve ağa dağıtan güçlü bilgisayar." },
    { kelime: "SİBER", ipucu: "İnternete ve bilgisayar ağlarına ait olan." },
    { kelime: "VERİ", ipucu: "İşlenmemiş ham bilgi parçası." },
    { kelime: "MUSTAFA", ipucu: "Seçilmiş, seçkin anlamına gelen popüler bir erkek ismi." },
    { kelime: "ZEYNEP", ipucu: "Değerli taşlar veya babasının süsü anlamına gelen isim." },
    { kelime: "DENİZ", ipucu: "Hem mavi suları hem de bir insan ismini temsil eden kelime." },
    { kelime: "İSTANBUL", ipucu: "İki kıtayı birbirine bağlayan tarihi metropol." },
    { kelime: "ERZURUM", ipucu: "Doğu Anadolu'nun soğuğu ve cağ kebabıyla ünlü şehri." },
    { kelime: "ANTALYA", ipucu: "Türkiye'nin turizm başkenti sayılan kıyı şehri." },
    { kelime: "BUZDOLABI", ipucu: "Yiyecekleri taze tutmak için soğutan mutfak cihazı." },
    { kelime: "KUMANDA", ipucu: "Televizyonu oturduğunuz yerden yönetmenizi sağlayan cihaz." },
    { kelime: "MİKROSKOP", ipucu: "Gözle görülmeyecek kadar küçük canlıları inceleyen alet." },
    { kelime: "BUKALEMUN", ipucu: "Renk değiştirme özelliğiyle bilinen sürüngen." },
    { kelime: "PENGUEN", ipucu: "Güney kutbunda yaşayan, uçamayan ama çok iyi yüzen kuş." },
    { kelime: "ZÜRAFA", ipucu: "Dünyanın en uzun boyunlu kara hayvanı." },
    { kelime: "ANKARA", ipucu: "Türkiye Cumhuriyeti'nin başkenti." },
    { kelime: "ASLAN", ipucu: "Ormanların kralı olarak bilinen yırtıcı kedi." },
    { kelime: "TELEFON", ipucu: "Haberleşmeyi sağlayan taşınabilir elektronik cihaz." },
    { kelime: "İZMİR", ipucu: "Ege'nin incisi olarak bilinen kıyı şehri." },
    { kelime: "KOLTUK", ipucu: "Üzerine oturulan rahat eşya." },
    { kelime: "FİL", ipucu: "Hortumuyla bilinen devasa kara memelisi." },
    { kelime: "ELİF", ipucu: "Arap alfabesinin ilk harfi olan kadın ismi." },
    { kelime: "BİLGİSAYAR", ipucu: "Veri işleyen, günümüzün en önemli teknolojik aleti." },
    { kelime: "KANGURU", ipucu: "Avustralya'ya özgü, keseli ve zıplayan hayvan." },
    { kelime: "BURSA", ipucu: "Osmanlı'ya başkentlik yapmış, yeşiliyle ünlü şehrimiz." },
    { kelime: "KULAKLIK", ipucu: "Müzik dinlemek için kulağa takılan cihaz." },
    { kelime: "KEREM", ipucu: "Aslı ile hikayesi olan, cömertlik anlamına gelen isim." },
    { kelime: "KAPLAN", ipucu: "Çizgili kürküyle bilinen büyük avcı." },
    { kelime: "ADANA", ipucu: "Kebabıyla meşhur, sıcak iklimli şehrimiz." },
    { kelime: "MASA", ipucu: "Üzerinde yemek yenilen veya çalışılan mobilya." },
    { kelime: "KARTAL", ipucu: "Keskin gözleri ve pençeleri olan yırtıcı kuş." },
    { kelime: "MERVE", ipucu: "Mekke'de bir tepenin adı olan yaygın kadın ismi." },
    { kelime: "ÜTÜ", ipucu: "Kırışık kıyafetleri düzeltmeye yarayan ısıtmalı alet." },
    { kelime: "BALİNA", ipucu: "Okyanuslarda yaşayan en büyük memeli hayvan." },
    { kelime: "TRABZON", ipucu: "Karadeniz'in fındığı ve hamsisiyle ünlü şehri." },
    { kelime: "SAAT", ipucu: "Zamanı ölçmeye yarayan araç." },
    { kelime: "AYI", ipucu: "Kış uykusuna yatmasıyla bilinen iri memeli." },
    { kelime: "YUSUF", ipucu: "Güzelliğiyle bilinen peygamber ismi." },
    { kelime: "DİYARBAKIR", ipucu: "Surları ve karpuzuyla ünlü kadim şehir." },
    { kelime: "AYNA", ipucu: "Baktığınızda kendinizi gördüğünüz cam nesne." },
    { kelime: "MAYMUN", ipucu: "İnsanlara benzerliği ve tırmanma yeteneğiyle bilinen hayvan." },
    { kelime: "FATMA", ipucu: "Peygamber efendimizin kızının adı olan isim." },
    { kelime: "ESKİŞEHİR", ipucu: "Porsuk çayı ve öğrenci nüfusuyla bilinen ilimiz." },
    { kelime: "SÜPÜRGE", ipucu: "Yerdeki tozları temizlemeye yarayan araç." },
    { kelime: "TİMSAH", ipucu: "Hem suda hem karada yaşayan, güçlü çeneli sürüngen." },
    { kelime: "ÖMER", ipucu: "Adaletiyle tanınan halifenin ismi." },
    { kelime: "MARDİN", ipucu: "Taş evleri ve tarihi dokusuyla ünlü güneydoğu şehri." },
    { kelime: "GÖZLÜK", ipucu: "Görmeyi netleştiren veya güneşten koruyan aksesuar." },
    { kelime: "PANDA", ipucu: "Bambu yiyen, siyah-beyaz renkli sevimli hayvan." },
    { kelime: "CAN", ipucu: "Yaşam, ruh anlamına gelen kısa erkek ismi." },
    { kelime: "KONYA", ipucu: "Mevlana Müzesi'ne ev sahipliği yapan ilimiz." },
    { kelime: "KAŞIK", ipucu: "Çorba içmek için kullanılan mutfak gereci." },
    { kelime: "KURT", ipucu: "Sürüler halinde yaşayan, köpekgillerden bir avcı." },
    { kelime: "AYŞE", ipucu: "Yaşam sürdüren, rahat yaşayan anlamındaki kadın ismi." },
    { kelime: "SİVAS", ipucu: "Cumhuriyet temellerinin atıldığı, soğuğuyla ünlü şehir." },
    { kelime: "PERDE", ipucu: "Pencereyi kapatmaya yarayan kumaş." },
    { kelime: "KAPLUMBAĞA", ipucu: "Sırtında eviyle yavaş yürüyen hayvan." },
    { kelime: "MURAT", ipucu: "İstek, arzu anlamına gelen erkek ismi." },
    { kelime: "GAZİANTEP", ipucu: "Gastronomi dünyasında baklavasıyla devleşen şehir." },
    { kelime: "CÜZDAN", ipucu: "Para ve kartların konulduğu küçük kılıf." },
    { kelime: "KOALA", ipucu: "Okaliptüs yaprağı yiyen, uykucu Avustralya hayvanı." },
    { kelime: "PELİN", ipucu: "Bir bitki adı olan kadın ismi." },
    { kelime: "EDİRNE", ipucu: "Selimiye Camii'nin bulunduğu serhat şehrimiz." },
    { kelime: "KALEM", ipucu: "Yazı yazmaya yarayan araç." },
    { kelime: "TAVŞAN", ipucu: "Havuç seven, uzun kulaklı hızlı hayvan." },
    { kelime: "ARDA", ipucu: "İşaret olarak dikilen değnek, halef anlamındaki isim." },
    { kelime: "AYDIN", ipucu: "Ege bölgesinin inciriyle ünlü şehri." },
    { kelime: "LAMBA", ipucu: "Işık vermeye yarayan eşya." },
    { kelime: "YILAN", ipucu: "Ayakları olmayan, sürünerek hareket eden hayvan." },
    { kelime: "BURCU", ipucu: "Güzel koku anlamına gelen kadın ismi." },
    { kelime: "ÇANAKKALE", ipucu: "Geçilmez destanının yazıldığı tarihi şehrimiz." },
    { kelime: "ANAHTAR", ipucu: "Kilidi açmaya yarayan metal nesne." },
    { kelime: "KÖPEK", ipucu: "İnsanın en sadık dostu olarak bilinen hayvan." },
    { kelime: "MEHMET", ipucu: "Muhammed isminin Türkçedeki yaygın hali." },
    { kelime: "KAYSERİ", ipucu: "Mantısı ve pastırmasıyla ünlü İç Anadolu şehri." },
    { kelime: "HALI", ipucu: "Yere serilen, desenli dokuma eşya." },
    { kelime: "KEDİ", ipucu: "Evlerde beslenen, mırlamasıyla bilinen hayvan." },
    { kelime: "YASEMİN", ipucu: "Güzel kokulu bir çiçek adı olan isim." },
    { kelime: "MUĞLA", ipucu: "Bodrum ve Marmaris gibi tatil yerlerini barındıran il." },
    { kelime: "MAKAS", ipucu: "Kağıt veya kumaş kesmeye yarayan araç." },
    { kelime: "TAVUK", ipucu: "Yumurtasından faydalanılan kümes hayvanı." },
    { kelime: "EMRE", ipucu: "Aşık, vurgun anlamına gelen erkek ismi." },
    { kelime: "ORDU", ipucu: "Fındığın başkenti olarak bilinen Karadeniz şehri." },
    { kelime: "SÜRAHİ", ipucu: "Su koymaya yarayan geniş gövdeli kap." },
    { kelime: "DEVE", ipucu: "Hörgücü sayesinde çölde susuzluğa dayanan hayvan." },
    { kelime: "GİZEM", ipucu: "Sır, bilinmeyen şey anlamına gelen isim." },
    { kelime: "DENİZLİ", ipucu: "Travertenleri ve horozuyla ünlü şehrimiz." },
    { kelime: "RADYO", ipucu: "Ses yayınlarını dinlemeye yarayan cihaz." },
    { kelime: "KELEBEK", ipucu: "Tırtıldan dönüşen, kanatlı narin böcek." },
    { kelime: "BATUHAN", ipucu: "Güçlü hükümdar anlamına gelen isim." },
    { kelime: "HATAY", ipucu: "Künefesi ve medeniyetler sofrasıyla ünlü il." },
    { kelime: "ÇANTA", ipucu: "Eşyaları taşımaya yarayan kılıf." },
    { kelime: "MAYMUN", ipucu: "Muz seven, ağaçlara tırmanan zeki hayvan." },
    { kelime: "SELİN", ipucu: "Gür akan su anlamına gelen kadın ismi." },
    { kelime: "VAN", ipucu: "Gölü ve kedisiyle ünlü doğu şehrimiz." }
];
 