const kelimeListesi = [
    { kelime: "YAZILIMCI", ipucu: "Bir meslek." },
    { kelime: "ARAYÜZ", ipucu: "Bilgisayarla ilgili bir kelime." },
    { kelime: "İSTİSNA", ipucu: "Soyut bir kavram." },
    { kelime: "DONANIM", ipucu: "Bilgisayarla ilgili bir kelime." },
    { kelime: "ALGORİTMA", ipucu: "Bilgisayarla ilgili bir kelime." },
    { kelime: "SUNUCU", ipucu: "Bilgisayarla ilgili bir kelime." },
    { kelime: "SİBER", ipucu: "Teknolojiyle ilgili bir kelime." },
    { kelime: "VERİ", ipucu: "Bilgisayarla ilgili bir kelime." },
    { kelime: "MUSTAFA", ipucu: "Bir isim." },
    { kelime: "ZEYNEP", ipucu: "Bir isim." },
    { kelime: "DENİZ", ipucu: "Hem bir isim hem bir doğa kelimesi." },
    { kelime: "İSTANBUL", ipucu: "Bir şehir." },
    { kelime: "ERZURUM", ipucu: "Doğu Anadolu'da bir il." },
    { kelime: "ANTALYA", ipucu: "Akdeniz'de bir il." },
    { kelime: "BUZDOLABI", ipucu: "Mutfakta bulunan bir eşya." },
    { kelime: "KUMANDA", ipucu: "Evde kullanılan bir eşya." },
    { kelime: "MİKROSKOP", ipucu: "Bilimle ilgili bir alet." },
    { kelime: "BUKALEMUN", ipucu: "Bir hayvan." },
    { kelime: "PENGUEN", ipucu: "Bir hayvan." },
    { kelime: "ZÜRAFA", ipucu: "Bir hayvan." },
    { kelime: "ANKARA", ipucu: "Bir şehir." },
    { kelime: "ASLAN", ipucu: "Bir hayvan." },
    { kelime: "TELEFON", ipucu: "Elektronik bir eşya." },
    { kelime: "İZMİR", ipucu: "Ege'de bir il." },
    { kelime: "KOLTUK", ipucu: "Evde bulunan bir eşya." },
    { kelime: "FİL", ipucu: "Bir hayvan." },
    { kelime: "ELİF", ipucu: "Bir isim." },
    { kelime: "BİLGİSAYAR", ipucu: "Elektronik bir eşya." },
    { kelime: "KANGURU", ipucu: "Bir hayvan." },
    { kelime: "BURSA", ipucu: "Marmara'da bir il." },
    { kelime: "KULAKLIK", ipucu: "Elektronik bir eşya." },
    { kelime: "KEREM", ipucu: "Bir isim." },
    { kelime: "KAPLAN", ipucu: "Bir hayvan." },
    { kelime: "ADANA", ipucu: "Akdeniz'de bir il." },
    { kelime: "MASA", ipucu: "Evde bulunan bir eşya." },
    { kelime: "KARTAL", ipucu: "Bir hayvan." },
    { kelime: "MERVE", ipucu: "Bir isim." },
    { kelime: "ÜTÜ", ipucu: "Evde kullanılan bir eşya." },
    { kelime: "BALİNA", ipucu: "Bir hayvan." },
    { kelime: "TRABZON", ipucu: "Karadeniz'de bir il." },
    { kelime: "SAAT", ipucu: "Günlük kullanılan bir eşya." },
    { kelime: "AYI", ipucu: "Bir hayvan." },
    { kelime: "YUSUF", ipucu: "Bir isim." },
    { kelime: "DİYARBAKIR", ipucu: "Güneydoğu Anadolu'da bir il." },
    { kelime: "AYNA", ipucu: "Evde bulunan bir eşya." },
    { kelime: "MAYMUN", ipucu: "Bir hayvan." },
    { kelime: "FATMA", ipucu: "Bir isim." },
    { kelime: "ESKİŞEHİR", ipucu: "İç Anadolu'da bir il." },
    { kelime: "SÜPÜRGE", ipucu: "Temizlikte kullanılan bir eşya." },
    { kelime: "TİMSAH", ipucu: "Bir hayvan." },
    { kelime: "ÖMER", ipucu: "Bir isim." },
    { kelime: "MARDİN", ipucu: "Güneydoğu Anadolu'da bir il." },
    { kelime: "GÖZLÜK", ipucu: "Yüzde takılan bir eşya." },
    { kelime: "PANDA", ipucu: "Bir hayvan." },
    { kelime: "CAN", ipucu: "Bir isim." },
    { kelime: "KONYA", ipucu: "İç Anadolu'da bir il." },
    { kelime: "KAŞIK", ipucu: "Mutfakta kullanılan bir eşya." },
    { kelime: "KURT", ipucu: "Bir hayvan." },
    { kelime: "AYŞE", ipucu: "Bir isim." },
    { kelime: "SİVAS", ipucu: "İç Anadolu'da bir il." },
    { kelime: "PERDE", ipucu: "Evde bulunan bir eşya." },
    { kelime: "KAPLUMBAĞA", ipucu: "Bir hayvan." },
    { kelime: "MURAT", ipucu: "Bir isim." },
    { kelime: "GAZİANTEP", ipucu: "Güneydoğu Anadolu'da bir il." },
    { kelime: "CÜZDAN", ipucu: "Günlük taşınan bir eşya." },
    { kelime: "KOALA", ipucu: "Bir hayvan." },
    { kelime: "PELİN", ipucu: "Bir isim." },
    { kelime: "EDİRNE", ipucu: "Marmara'da bir il." },
    { kelime: "KALEM", ipucu: "Okulda kullanılan bir eşya." },
    { kelime: "TAVŞAN", ipucu: "Bir hayvan." },
    { kelime: "ARDA", ipucu: "Bir isim." },
    { kelime: "AYDIN", ipucu: "Ege'de bir il." },
    { kelime: "LAMBA", ipucu: "Evde bulunan bir eşya." },
    { kelime: "YILAN", ipucu: "Bir hayvan." },
    { kelime: "BURCU", ipucu: "Bir isim." },
    { kelime: "ÇANAKKALE", ipucu: "Marmara'da bir il." },
    { kelime: "ANAHTAR", ipucu: "Günlük kullanılan bir eşya." },
    { kelime: "KÖPEK", ipucu: "Bir hayvan." },
    { kelime: "MEHMET", ipucu: "Bir isim." },
    { kelime: "KAYSERİ", ipucu: "İç Anadolu'da bir il." },
    { kelime: "HALI", ipucu: "Evde bulunan bir eşya." },
    { kelime: "KEDİ", ipucu: "Bir hayvan." },
    { kelime: "YASEMİN", ipucu: "Bir isim." },
    { kelime: "MUĞLA", ipucu: "Ege'de bir il." },
    { kelime: "MAKAS", ipucu: "Günlük kullanılan bir eşya." },
    { kelime: "TAVUK", ipucu: "Bir hayvan." },
    { kelime: "EMRE", ipucu: "Bir isim." },
    { kelime: "ORDU", ipucu: "Karadeniz'de bir il." },
    { kelime: "SÜRAHİ", ipucu: "Mutfakta kullanılan bir eşya." },
    { kelime: "DEVE", ipucu: "Bir hayvan." },
    { kelime: "GİZEM", ipucu: "Bir isim." },
    { kelime: "DENİZLİ", ipucu: "Ege'de bir il." },
    { kelime: "RADYO", ipucu: "Elektronik bir eşya." },
    { kelime: "KELEBEK", ipucu: "Bir böcek." },
    { kelime: "BATUHAN", ipucu: "Bir isim." },
    { kelime: "HATAY", ipucu: "Akdeniz'de bir il." },
    { kelime: "ÇANTA", ipucu: "Günlük taşınan bir eşya." },
    { kelime: "SELİN", ipucu: "Bir isim." },
    { kelime: "VAN", ipucu: "Doğu Anadolu'da bir il." },

    { kelime: "AHMET", ipucu: "Bir isim." },
    { kelime: "MEHTAP", ipucu: "Bir isim." },
    { kelime: "CEREN", ipucu: "Bir isim." },
    { kelime: "BERK", ipucu: "Bir isim." },
    { kelime: "İREM", ipucu: "Bir isim." },
    { kelime: "KAAN", ipucu: "Bir isim." },
    { kelime: "DİLARA", ipucu: "Bir isim." },
    { kelime: "EFE", ipucu: "Bir isim." },
    { kelime: "NİSA", ipucu: "Bir isim." },
    { kelime: "ALPEREN", ipucu: "Bir isim." },
    { kelime: "SUDE", ipucu: "Bir isim." },
    { kelime: "TOPRAK", ipucu: "Bir doğa kelimesi." },
    { kelime: "İLKNUR", ipucu: "Bir isim." },
    { kelime: "OZAN", ipucu: "Bir isim." },
    { kelime: "ESRA", ipucu: "Bir isim." },
    { kelime: "KEMAL", ipucu: "Bir isim." },
    { kelime: "NAZLI", ipucu: "Bir isim." },
    { kelime: "BORA", ipucu: "Bir isim." },
    { kelime: "AYBÜKE", ipucu: "Bir isim." },
    { kelime: "SERHAT", ipucu: "Bir isim." },
    { kelime: "GAMZE", ipucu: "Bir isim." },
    { kelime: "TARKAN", ipucu: "Bir isim." },
    { kelime: "İDİL", ipucu: "Bir isim." },
    { kelime: "ONUR", ipucu: "Bir isim." },
    { kelime: "PEMBE", ipucu: "Bir renk." },
    { kelime: "MOR", ipucu: "Bir renk." },
    { kelime: "TURUNCU", ipucu: "Bir renk." },
    { kelime: "SARI", ipucu: "Bir renk." },
    { kelime: "SİYAH", ipucu: "Bir renk." },
    { kelime: "BEYAZ", ipucu: "Bir renk." },
    { kelime: "ELMA", ipucu: "Bir meyve." },
    { kelime: "MUZ", ipucu: "Bir meyve." },
    { kelime: "KARPUZ", ipucu: "Bir meyve." },
    { kelime: "ÇİLEK", ipucu: "Bir meyve." },
    { kelime: "PORTAKAL", ipucu: "Bir meyve." },
    { kelime: "ÜZÜM", ipucu: "Bir meyve." },
    { kelime: "ARMUT", ipucu: "Bir meyve." },
    { kelime: "KİRAZ", ipucu: "Bir meyve." },
    { kelime: "NAR", ipucu: "Bir meyve." },
    { kelime: "AYVA", ipucu: "Bir meyve." },
    { kelime: "PATATES", ipucu: "Bir sebze." },
    { kelime: "DOMATES", ipucu: "Bir sebze." },
    { kelime: "SOĞAN", ipucu: "Bir sebze." },
    { kelime: "PATLICAN", ipucu: "Bir sebze." },
    { kelime: "BİBER", ipucu: "Bir sebze." },
    { kelime: "HAVUÇ", ipucu: "Bir sebze." },
    { kelime: "SALATALIK", ipucu: "Bir sebze." },
    { kelime: "KABAK", ipucu: "Bir sebze." },
    { kelime: "EKMEK", ipucu: "Bir besin." },
    { kelime: "PEYNİR", ipucu: "Bir besin." },
    { kelime: "BAL", ipucu: "Bir besin." },
    { kelime: "ZEYTİN", ipucu: "Bir besin." },
    { kelime: "ÇAY", ipucu: "Bir içecek." },
    { kelime: "KAHVE", ipucu: "Bir içecek." },
    { kelime: "SÜT", ipucu: "Bir içecek." },
    { kelime: "PASTA", ipucu: "Bir tatlı." },
    { kelime: "DONDURMA", ipucu: "Bir tatlı." },
    { kelime: "ÇİKOLATA", ipucu: "Bir tatlı." },
    { kelime: "BULUT", ipucu: "Gökyüzüyle ilgili bir kelime." },
    { kelime: "YAĞMUR", ipucu: "Bir hava olayı." },
    { kelime: "KAR", ipucu: "Bir hava olayı." },
    { kelime: "GÜNEŞ", ipucu: "Gökyüzüyle ilgili bir kelime." },
    { kelime: "AY", ipucu: "Gökyüzüyle ilgili bir kelime." },
    { kelime: "YILDIZ", ipucu: "Gökyüzüyle ilgili bir kelime." },
    { kelime: "GÖKKUŞAĞI", ipucu: "Gökyüzüyle ilgili bir kelime." },
    { kelime: "RÜZGAR", ipucu: "Bir hava olayı." },
    { kelime: "ORMAN", ipucu: "Bir doğa kelimesi." },
    { kelime: "DAĞ", ipucu: "Bir doğa kelimesi." },
    { kelime: "NEHİR", ipucu: "Bir doğa kelimesi." },
    { kelime: "GÖL", ipucu: "Bir doğa kelimesi." },
    { kelime: "ÇÖL", ipucu: "Bir doğa kelimesi." },
    { kelime: "ADA", ipucu: "Bir doğa kelimesi." },
    { kelime: "VOLKAN", ipucu: "Bir doğa kelimesi." },
    { kelime: "FUTBOL", ipucu: "Bir spor dalı." },
    { kelime: "BASKETBOL", ipucu: "Bir spor dalı." },
    { kelime: "YÜZME", ipucu: "Bir spor dalı." },
    { kelime: "BİSİKLET", ipucu: "Bir araç." },
    { kelime: "GİTAR", ipucu: "Bir müzik aleti." },
    { kelime: "PİYANO", ipucu: "Bir müzik aleti." },
    { kelime: "DAVUL", ipucu: "Bir müzik aleti." },
    { kelime: "KEMAN", ipucu: "Bir müzik aleti." },
    { kelime: "OKUL", ipucu: "Bir kurum." },
    { kelime: "ÖĞRETMEN", ipucu: "Bir meslek." },
    { kelime: "DOKTOR", ipucu: "Bir meslek." },
    { kelime: "MÜHENDİS", ipucu: "Bir meslek." },
    { kelime: "AŞÇI", ipucu: "Bir meslek." },
    { kelime: "PİLOT", ipucu: "Bir meslek." },
    { kelime: "İTFAİYECİ", ipucu: "Bir meslek." },
    { kelime: "POLİS", ipucu: "Bir meslek." },
    { kelime: "BERBER", ipucu: "Bir meslek." },
    { kelime: "TERZİ", ipucu: "Bir meslek." },
    { kelime: "MARANGOZ", ipucu: "Bir meslek." },
    { kelime: "UÇAK", ipucu: "Bir taşıt." },
    { kelime: "GEMİ", ipucu: "Bir taşıt." },
    { kelime: "TREN", ipucu: "Bir taşıt." },
    { kelime: "OTOBÜS", ipucu: "Bir taşıt." },
    { kelime: "BİSİKLETÇİ", ipucu: "Bir spor dalıyla uğraşan kişi." },
    { kelime: "KİTAP", ipucu: "Okulda kullanılan bir eşya." },
    { kelime: "DEFTER", ipucu: "Okulda kullanılan bir eşya." },
    { kelime: "SİLGİ", ipucu: "Okulda kullanılan bir eşya." },
    { kelime: "CETVEL", ipucu: "Okulda kullanılan bir eşya." },
    { kelime: "BOYA", ipucu: "Okulda kullanılan bir eşya." },
    { kelime: "FIRÇA", ipucu: "Günlük kullanılan bir eşya." },
    { kelime: "ÇİÇEK", ipucu: "Bir bitki." },
    { kelime: "GÜL", ipucu: "Bir çiçek." },
    { kelime: "LALE", ipucu: "Bir çiçek." },
    { kelime: "AĞAÇ", ipucu: "Bir bitki." },
    { kelime: "YAPRAK", ipucu: "Bitkiyle ilgili bir kelime." },
    { kelime: "ARI", ipucu: "Bir böcek." },
    { kelime: "KARINCA", ipucu: "Bir böcek." },
    { kelime: "ÖRÜMCEK", ipucu: "Bir böcek." },
    { kelime: "BALIK", ipucu: "Bir hayvan." },
    { kelime: "KUŞ", ipucu: "Bir hayvan." },
    { kelime: "PAPAĞAN", ipucu: "Bir hayvan." },
    { kelime: "TAVUSKUŞU", ipucu: "Bir hayvan." },
    { kelime: "İNEK", ipucu: "Bir hayvan." },
    { kelime: "KOYUN", ipucu: "Bir hayvan." },
    { kelime: "AT", ipucu: "Bir hayvan." },
    { kelime: "EŞEK", ipucu: "Bir hayvan." },
    { kelime: "TAVŞANCIK", ipucu: "Bir hayvan." },
    { kelime: "İĞNE", ipucu: "Günlük kullanılan bir eşya." },
    { kelime: "MUM", ipucu: "Evde bulunan bir eşya." },
    { kelime: "ŞEMSİYE", ipucu: "Günlük kullanılan bir eşya." },
    { kelime: "TERLİK", ipucu: "Evde giyilen bir eşya." },
    { kelime: "YASTIK", ipucu: "Evde bulunan bir eşya." },
    { kelime: "YORGAN", ipucu: "Evde bulunan bir eşya." },
    { kelime: "DOLAP", ipucu: "Evde bulunan bir eşya." },
    { kelime: "PENCERE", ipucu: "Evin bir parçası." },
    { kelime: "KAPI", ipucu: "Evin bir parçası." },
    { kelime: "MERDİVEN", ipucu: "Evin bir parçası." },
    { kelime: "BAHÇE", ipucu: "Evin bir parçası." },
    { kelime: "BALKON", ipucu: "Evin bir parçası." },

    { kelime: "AMERİKA", ipucu: "Bir ülke." },
    { kelime: "FRANSA", ipucu: "Bir ülke." },
    { kelime: "ALMANYA", ipucu: "Bir ülke." },
    { kelime: "İTALYA", ipucu: "Bir ülke." },
    { kelime: "İSPANYA", ipucu: "Bir ülke." },
    { kelime: "İNGİLTERE", ipucu: "Bir ülke." },
    { kelime: "YUNANİSTAN", ipucu: "Bir ülke." },
    { kelime: "RUSYA", ipucu: "Bir ülke." },
    { kelime: "ÇİN", ipucu: "Bir ülke." },
    { kelime: "JAPONYA", ipucu: "Bir ülke." },
    { kelime: "HİNDİSTAN", ipucu: "Bir ülke." },
    { kelime: "MISIR", ipucu: "Bir ülke." },
    { kelime: "BREZİLYA", ipucu: "Bir ülke." },
    { kelime: "KANADA", ipucu: "Bir ülke." },
    { kelime: "MEKSİKA", ipucu: "Bir ülke." },
    { kelime: "HOLLANDA", ipucu: "Bir ülke." },
    { kelime: "PORTEKİZ", ipucu: "Bir ülke." },
    { kelime: "İSVEÇ", ipucu: "Bir ülke." },
    { kelime: "NORVEÇ", ipucu: "Bir ülke." },
    { kelime: "İSVİÇRE", ipucu: "Bir ülke." },
    { kelime: "AVUSTURYA", ipucu: "Bir ülke." },
    { kelime: "BELÇİKA", ipucu: "Bir ülke." },
    { kelime: "POLONYA", ipucu: "Bir ülke." },
    { kelime: "UKRAYNA", ipucu: "Bir ülke." },
    { kelime: "SUUDİARABİSTAN", ipucu: "Bir ülke." },
    { kelime: "İRAN", ipucu: "Bir ülke." },
    { kelime: "IRAK", ipucu: "Bir ülke." },
    { kelime: "SURİYE", ipucu: "Bir ülke." },
    { kelime: "AZERBAYCAN", ipucu: "Bir ülke." },
    { kelime: "GÜRCİSTAN", ipucu: "Bir ülke." },
    { kelime: "AVUSTRALYA", ipucu: "Bir ülke." },
    { kelime: "ARJANTİN", ipucu: "Bir ülke." },
    { kelime: "GÜNEYAFRİKA", ipucu: "Bir ülke." },
    { kelime: "FAS", ipucu: "Bir ülke." },
    { kelime: "PAKİSTAN", ipucu: "Bir ülke." },

    { kelime: "PARİS", ipucu: "Bir başkent." },
    { kelime: "LONDRA", ipucu: "Bir başkent." },
    { kelime: "ROMA", ipucu: "Bir başkent." },
    { kelime: "BERLİN", ipucu: "Bir başkent." },
    { kelime: "MADRİD", ipucu: "Bir başkent." },
    { kelime: "ATİNA", ipucu: "Bir başkent." },
    { kelime: "MOSKOVA", ipucu: "Bir başkent." },
    { kelime: "TOKYO", ipucu: "Bir başkent." },
    { kelime: "KAHİRE", ipucu: "Bir başkent." },
    { kelime: "PEKİN", ipucu: "Bir başkent." },
    { kelime: "AMSTERDAM", ipucu: "Bir başkent." },
    { kelime: "LİZBON", ipucu: "Bir başkent." },
    { kelime: "VİYANA", ipucu: "Bir başkent." },
    { kelime: "BRÜKSEL", ipucu: "Bir başkent." },
    { kelime: "VARŞOVA", ipucu: "Bir başkent." },
    { kelime: "STOKHOLM", ipucu: "Bir başkent." },

    { kelime: "SAMSUN", ipucu: "Karadeniz'de bir il." },
    { kelime: "RİZE", ipucu: "Karadeniz'de bir il." },
    { kelime: "ZONGULDAK", ipucu: "Karadeniz'de bir il." },
    { kelime: "SİNOP", ipucu: "Karadeniz'de bir il." },
    { kelime: "BOLU", ipucu: "Karadeniz'de bir il." },
    { kelime: "KOCAELİ", ipucu: "Marmara'da bir il." },
    { kelime: "TEKİRDAĞ", ipucu: "Marmara'da bir il." },
    { kelime: "BALIKESİR", ipucu: "Marmara'da bir il." },
    { kelime: "MANİSA", ipucu: "Ege'de bir il." },
    { kelime: "UŞAK", ipucu: "Ege'de bir il." },
    { kelime: "AFYON", ipucu: "Ege'de bir il." },
    { kelime: "ISPARTA", ipucu: "Akdeniz'de bir il." },
    { kelime: "MERSİN", ipucu: "Akdeniz'de bir il." },
    { kelime: "KAHRAMANMARAŞ", ipucu: "Akdeniz'de bir il." },
    { kelime: "NİĞDE", ipucu: "İç Anadolu'da bir il." },
    { kelime: "KIRŞEHİR", ipucu: "İç Anadolu'da bir il." },
    { kelime: "YOZGAT", ipucu: "İç Anadolu'da bir il." },
    { kelime: "ÇORUM", ipucu: "Karadeniz'de bir il." },
    { kelime: "AMASYA", ipucu: "Karadeniz'de bir il." },
    { kelime: "TOKAT", ipucu: "Karadeniz'de bir il." },
    { kelime: "MALATYA", ipucu: "Doğu Anadolu'da bir il." },
    { kelime: "ELAZIĞ", ipucu: "Doğu Anadolu'da bir il." },
    { kelime: "KARS", ipucu: "Doğu Anadolu'da bir il." },
    { kelime: "AĞRI", ipucu: "Doğu Anadolu'da bir il." },
    { kelime: "BATMAN", ipucu: "Güneydoğu Anadolu'da bir il." },
    { kelime: "ŞANLIURFA", ipucu: "Güneydoğu Anadolu'da bir il." },
    { kelime: "SİİRT", ipucu: "Güneydoğu Anadolu'da bir il." },
    { kelime: "BODRUM", ipucu: "Bir tatil beldesi." },
    { kelime: "MARMARİS", ipucu: "Bir tatil beldesi." },
    { kelime: "ALANYA", ipucu: "Bir tatil beldesi." },
    { kelime: "KUŞADASI", ipucu: "Bir tatil beldesi." },
    { kelime: "ÇEŞME", ipucu: "Bir tatil beldesi." },

    { kelime: "ADEM", ipucu: "Bir isim." },
    { kelime: "HASAN", ipucu: "Bir isim." },
    { kelime: "HÜSEYİN", ipucu: "Bir isim." },
    { kelime: "İBRAHİM", ipucu: "Bir isim." },
    { kelime: "İSMAİL", ipucu: "Bir isim." },
    { kelime: "SELÇUK", ipucu: "Bir isim." },
    { kelime: "SERKAN", ipucu: "Bir isim." },
    { kelime: "YAVUZ", ipucu: "Bir isim." },
    { kelime: "CEMAL", ipucu: "Bir isim." },
    { kelime: "HAKAN", ipucu: "Bir isim." },
    { kelime: "ÖZLEM", ipucu: "Bir isim." },
    { kelime: "SEDA", ipucu: "Bir isim." },
    { kelime: "PINAR", ipucu: "Bir isim." },
    { kelime: "BUSE", ipucu: "Bir isim." },
    { kelime: "ELİFNUR", ipucu: "Bir isim." },
    { kelime: "MELİS", ipucu: "Bir isim." },
    { kelime: "DUYGU", ipucu: "Bir isim." },
    { kelime: "HANDE", ipucu: "Bir isim." },
    { kelime: "SEVGİ", ipucu: "Bir isim." },
    { kelime: "AYLİN", ipucu: "Bir isim." },
    { kelime: "TUANA", ipucu: "Bir isim." },
    { kelime: "ECE", ipucu: "Bir isim." },
    { kelime: "DEFNE", ipucu: "Bir isim." },
    { kelime: "AZRA", ipucu: "Bir isim." },
    { kelime: "EYLÜL", ipucu: "Bir isim." },
    { kelime: "MİRAY", ipucu: "Bir isim." },
    { kelime: "ASYA", ipucu: "Bir isim." },
    { kelime: "YİĞİT", ipucu: "Bir isim." },
    { kelime: "ATA", ipucu: "Bir isim." },
    { kelime: "ÇINAR", ipucu: "Bir isim." },
    { kelime: "DORUK", ipucu: "Bir isim." },

    { kelime: "AYAKKABI", ipucu: "Ayağa giyilen bir eşya." },
    { kelime: "PANTOLON", ipucu: "Giyilen bir eşya." },
    { kelime: "GÖMLEK", ipucu: "Giyilen bir eşya." },
    { kelime: "ELBİSE", ipucu: "Giyilen bir eşya." },
    { kelime: "ŞAPKA", ipucu: "Başa giyilen bir eşya." },
    { kelime: "ATKI", ipucu: "Boyuna sarılan bir eşya." },
    { kelime: "ELDİVEN", ipucu: "Ele giyilen bir eşya." },
    { kelime: "KEMER", ipucu: "Bele takılan bir eşya." },
    { kelime: "YÜZÜK", ipucu: "Parmağa takılan bir eşya." },
    { kelime: "KOLYE", ipucu: "Boyuna takılan bir eşya." },
    { kelime: "KÜPE", ipucu: "Kulağa takılan bir eşya." },

    { kelime: "AKORDEON", ipucu: "Bir müzik aleti." },
    { kelime: "FLÜT", ipucu: "Bir müzik aleti." },
    { kelime: "SAKSOFON", ipucu: "Bir müzik aleti." },
    { kelime: "TROMPET", ipucu: "Bir müzik aleti." },
    { kelime: "BAĞLAMA", ipucu: "Bir müzik aleti." },
    { kelime: "DARBUKA", ipucu: "Bir müzik aleti." },
    { kelime: "NEY", ipucu: "Bir müzik aleti." },

    { kelime: "VOLEYBOL", ipucu: "Bir spor dalı." },
    { kelime: "TENİS", ipucu: "Bir spor dalı." },
    { kelime: "GÜREŞ", ipucu: "Bir spor dalı." },
    { kelime: "BOKS", ipucu: "Bir spor dalı." },
    { kelime: "ATLETİZM", ipucu: "Bir spor dalı." },
    { kelime: "KAYAK", ipucu: "Bir spor dalı." },
    { kelime: "OKÇULUK", ipucu: "Bir spor dalı." },
    { kelime: "ESKRİM", ipucu: "Bir spor dalı." },

    { kelime: "AVUKAT", ipucu: "Bir meslek." },
    { kelime: "HAKİM", ipucu: "Bir meslek." },
    { kelime: "GAZETECİ", ipucu: "Bir meslek." },
    { kelime: "MİMAR", ipucu: "Bir meslek." },
    { kelime: "ECZACI", ipucu: "Bir meslek." },
    { kelime: "HEMŞİRE", ipucu: "Bir meslek." },
    { kelime: "ÇİFTÇİ", ipucu: "Bir meslek." },
    { kelime: "BALIKÇI", ipucu: "Bir meslek." },
    { kelime: "MUHASEBECİ", ipucu: "Bir meslek." },
    { kelime: "FOTOĞRAFÇI", ipucu: "Bir meslek." },
    { kelime: "RESSAM", ipucu: "Bir meslek." },
    { kelime: "YAZAR", ipucu: "Bir meslek." },
    { kelime: "OYUNCU", ipucu: "Bir meslek." },
    { kelime: "ŞARKICI", ipucu: "Bir meslek." },

    { kelime: "SAKSAĞAN", ipucu: "Bir hayvan." },
    { kelime: "SERÇE", ipucu: "Bir hayvan." },
    { kelime: "GÜVERCİN", ipucu: "Bir hayvan." },
    { kelime: "LEYLEK", ipucu: "Bir hayvan." },
    { kelime: "BAYKUŞ", ipucu: "Bir hayvan." },
    { kelime: "YARASA", ipucu: "Bir hayvan." },
    { kelime: "SANSAR", ipucu: "Bir hayvan." },
    { kelime: "TİLKİ", ipucu: "Bir hayvan." },
    { kelime: "GEYİK", ipucu: "Bir hayvan." },
    { kelime: "KEÇİ", ipucu: "Bir hayvan." },
    { kelime: "DOMUZ", ipucu: "Bir hayvan." },
    { kelime: "FARE", ipucu: "Bir hayvan." },
    { kelime: "SIÇAN", ipucu: "Bir hayvan." },
    { kelime: "HAMSTER", ipucu: "Bir hayvan." },
    { kelime: "SALYANGOZ", ipucu: "Bir hayvan." },
    { kelime: "AHTAPOT", ipucu: "Bir hayvan." },
    { kelime: "YENGEÇ", ipucu: "Bir hayvan." },
    { kelime: "İSTAKOZ", ipucu: "Bir hayvan." },
    { kelime: "DENİZYILDIZI", ipucu: "Bir hayvan." },
    { kelime: "KÖPEKBALIĞI", ipucu: "Bir hayvan." },
    { kelime: "YUNUS", ipucu: "Bir hayvan." },
    { kelime: "FOK", ipucu: "Bir hayvan." },

    { kelime: "KAYISI", ipucu: "Bir meyve." },
    { kelime: "ŞEFTALİ", ipucu: "Bir meyve." },
    { kelime: "İNCİR", ipucu: "Bir meyve." },
    { kelime: "MANDALİNA", ipucu: "Bir meyve." },
    { kelime: "GREYFURT", ipucu: "Bir meyve." },
    { kelime: "LİMON", ipucu: "Bir meyve." },
    { kelime: "AHUDUDU", ipucu: "Bir meyve." },
    { kelime: "BÖĞÜRTLEN", ipucu: "Bir meyve." },
    { kelime: "ANANAS", ipucu: "Bir meyve." },
    { kelime: "HİNDİSTANCEVİZİ", ipucu: "Bir meyve." },
    { kelime: "AVOKADO", ipucu: "Bir meyve." },
    { kelime: "MANGO", ipucu: "Bir meyve." },

    { kelime: "MARUL", ipucu: "Bir sebze." },
    { kelime: "LAHANA", ipucu: "Bir sebze." },
    { kelime: "BROKOLİ", ipucu: "Bir sebze." },
    { kelime: "PIRASA", ipucu: "Bir sebze." },
    { kelime: "TURP", ipucu: "Bir sebze." },
    { kelime: "PANCAR", ipucu: "Bir sebze." },
    { kelime: "MANTAR", ipucu: "Bir sebze." },
    { kelime: "BEZELYE", ipucu: "Bir sebze." },
    { kelime: "FASULYE", ipucu: "Bir sebze." },

    { kelime: "KIRMIZI", ipucu: "Bir renk." },
    { kelime: "MAVİ", ipucu: "Bir renk." },
    { kelime: "YEŞİL", ipucu: "Bir renk." },
    { kelime: "GRİ", ipucu: "Bir renk." },
    { kelime: "LACİVERT", ipucu: "Bir renk." },
    { kelime: "BEJ", ipucu: "Bir renk." },

    { kelime: "SANDALYE", ipucu: "Evde bulunan bir eşya." },
    { kelime: "RAF", ipucu: "Evde bulunan bir eşya." },
    { kelime: "VAZO", ipucu: "Evde bulunan bir eşya." },
    { kelime: "HALIFA", ipucu: "Tarihte geçen bir unvan." },
    { kelime: "SULTAN", ipucu: "Tarihte geçen bir unvan." },
    { kelime: "PADİŞAH", ipucu: "Tarihte geçen bir unvan." },
    { kelime: "KRAL", ipucu: "Bir unvan." },
    { kelime: "KRALİÇE", ipucu: "Bir unvan." },
    { kelime: "PRENS", ipucu: "Bir unvan." },
    { kelime: "PRENSES", ipucu: "Bir unvan." }
];
